package org.batfish.specifier.parboiled;

import static com.google.common.base.MoreObjects.toStringHelper;

import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;

/**
 * A class that represents an auto complete suggestion generated by {@link ParboiledAutoComplete}
 */
@ParametersAreNonnullByDefault
public final class ParboiledAutoCompleteSuggestion {

  /** The anchor based on which we are auto completing.   */
  @Nonnull Anchor.Type private final Anchor.Type _anchorType;

  /** Index in the input query string where the suggestion text should be inserted */
  private final int _insertionIndex;

  /** Actual text of the suggestion */
  @Nonnull private final String _text;

  public ParboiledAutoCompleteSuggestion(
      String text,
      int insertionIndex,
      Anchor.Type anchorType) {
    _text = text;
    _insertionIndex = insertionIndex;
    _anchorType = anchorType;
  }

  @Override
  public boolean equals(Object o) {
    if (!(o instanceof ParboiledAutoCompleteSuggestion)) {
      return false;
    }
    return Objects.equals(_anchorType, ((ParboiledAutoCompleteSuggestion) o)._anchorType)
        && Objects.equals(_insertionIndex, ((ParboiledAutoCompleteSuggestion) o)._insertionIndex),
        && Objects.equals(_text, ((ParboiledAutoCompleteSuggestion) o)._text);
  }

  @Nonnull
  public Anchor.Type getAnchorType() {
    return _anchorType;
  }

  public int getInsertionIndex() {
    return _insertionIndex;
  }

  @Nonnull
  public String getText() {
    return _text;
  }

  @Override
  public int hashCode() {
    return Objects.hash(_anchorType, _insertionIndex,  _text);
  }

  @Override
  public String toString() {
    return toStringHelper(getClass())
        .add("text", _text)
        .add("insertionIndex", _insertionIndex)
        .add("anchorType", _anchorType)
        .toString();
  }
}
