package org.batfish.specifier.parboiled;

import com.google.common.collect.Sets;
import java.util.Objects;
import java.util.Set;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import org.batfish.datamodel.routing_policy.RoutingPolicy;
import org.batfish.specifier.NameRegexRoutingPolicySpecifier;
import org.batfish.specifier.NameRoutingPolicySpecifier;
import org.batfish.specifier.RoutingPolicySpecifier;
import org.batfish.specifier.SpecifierContext;

/** An {@link RoutingPolicySpecifier} that resolves based on the AST generated by {@link Parser}. */
@ParametersAreNonnullByDefault
final class ParboiledRoutingPolicySpecifier implements RoutingPolicySpecifier {

  @ParametersAreNonnullByDefault
  private final class RoutingPolicyAstNodeToRoutingPolicys
      implements RoutingPolicyAstNodeVisitor<Set<RoutingPolicy>> {
    private final SpecifierContext _ctxt;
    private final String _node;

    RoutingPolicyAstNodeToRoutingPolicys(String node, SpecifierContext ctxt) {
      _node = node;
      _ctxt = ctxt;
    }

    @Nonnull
    @Override
    public Set<RoutingPolicy> visitDifferenceRoutingPolicyAstNode(
        DifferenceRoutingPolicyAstNode differenceRoutingPolicyAstNode) {
      return Sets.difference(
          differenceRoutingPolicyAstNode.getLeft().accept(this),
          differenceRoutingPolicyAstNode.getRight().accept(this));
    }

    @Nonnull
    @Override
    public Set<RoutingPolicy> visitIntersectionRoutingPolicyAstNode(
        IntersectionRoutingPolicyAstNode intersectionRoutingPolicyAstNode) {
      return Sets.intersection(
          intersectionRoutingPolicyAstNode.getLeft().accept(this),
          intersectionRoutingPolicyAstNode.getRight().accept(this));
    }

    @Nonnull
    @Override
    public Set<RoutingPolicy> visitNameRoutingPolicyAstNode(
        NameRoutingPolicyAstNode nameRoutingPolicyAstNode) {
      return new NameRoutingPolicySpecifier(nameRoutingPolicyAstNode.getName())
          .resolve(_node, _ctxt);
    }

    @Nonnull
    @Override
    public Set<RoutingPolicy> visitNameRegexRoutingPolicyAstNode(
        NameRegexRoutingPolicyAstNode nameRegexRoutingPolicyAstNode) {
      return new NameRegexRoutingPolicySpecifier(nameRegexRoutingPolicyAstNode.getPattern())
          .resolve(_node, _ctxt);
    }

    @Nonnull
    @Override
    public Set<RoutingPolicy> visitUnionRoutingPolicyAstNode(
        UnionRoutingPolicyAstNode unionRoutingPolicyAstNode) {
      return Sets.union(
          unionRoutingPolicyAstNode.getLeft().accept(this),
          unionRoutingPolicyAstNode.getRight().accept(this));
    }
  }

  private final RoutingPolicyAstNode _ast;

  ParboiledRoutingPolicySpecifier(RoutingPolicyAstNode ast) {
    _ast = ast;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ParboiledRoutingPolicySpecifier)) {
      return false;
    }
    return Objects.equals(_ast, ((ParboiledRoutingPolicySpecifier) o)._ast);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_ast);
  }

  @Override
  public Set<RoutingPolicy> resolve(String node, SpecifierContext ctxt) {
    return _ast.accept(new RoutingPolicyAstNodeToRoutingPolicys(node, ctxt));
  }
}
