package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "withdrawals_juniper",
    srcs = glob(
        ["**"],
        exclude = ["BUILD"],
    ),
)
