package(default_visibility = ["//visibility:public"])

load("@batfish//skylark:junit.bzl", "junit_tests")

java_library(
    name = "symbolic",
    exports = [
        "//projects/symbolic/src/main/java/org/batfish/symbolic:core",
        "//projects/symbolic/src/main/java/org/batfish/symbolic/state",
    ],
)
