githubRepoOwner: batfish
githubRepoName: batfish
githubHost: github.com
requireChecks: true
requireApproval: false
githubRemote: origin
githubBranch: master
remoteBranches: []
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
