/*
 * This file is a Java 17 port of the antlr4-c3 code-completion core, updated for
 * the ANTLR 4.13.2 runtime API. It is derived from the antlr4-c3 project
 * (https://github.com/mike-lischke/antlr4-c3), specifically:
 *   - the TypeScript reference implementation (src/CodeCompletionCore.ts),
 *     Copyright (c) Mike Lischke, and
 *   - the earlier Java port (ports/java/.../CodeCompletionCore.java),
 *     Copyright (c) 2017 VMware, Inc.
 * Both are licensed under the MIT License, retained here per that license.
 *
 * SPDX-License-Identifier: MIT
 */

package org.batfish.common.util.antlr4c3;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;
import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.atn.ATN;
import org.antlr.v4.runtime.atn.ATNState;
import org.antlr.v4.runtime.atn.PrecedencePredicateTransition;
import org.antlr.v4.runtime.atn.PredicateTransition;
import org.antlr.v4.runtime.atn.RuleStartState;
import org.antlr.v4.runtime.atn.RuleTransition;
import org.antlr.v4.runtime.atn.Transition;
import org.antlr.v4.runtime.misc.IntervalSet;

/**
 * Grammar-agnostic code-completion engine for ANTLR4 parsers. Given a parser and a caret token
 * index, it walks the ATN by taking every path (rather than using the prediction machinery) and
 * collects the token and rule candidates valid at the caret.
 *
 * <p>This is a modern Java port of <a
 * href="https://github.com/mike-lischke/antlr4-c3">antlr4-c3</a> targeting the ANTLR 4.13.2
 * runtime. It compiles as ordinary Java (unlike the parboiled parsers it is intended to replace,
 * whose runtime-generated bytecode crashes JaCoCo instrumentation).
 */
public class CodeCompletionCore {

  /**
   * A candidate rule: the token index where the rule started and the rule callstack to reach it.
   */
  public record CandidateRule(int startTokenIndex, List<Integer> ruleList) {}

  /**
   * The result of a collection run. {@code tokens} maps a candidate token type to the sequence of
   * tokens that directly follow it in the grammar (empty if not a fixed sequence). {@code rules}
   * maps a candidate preferred-rule index to the context in which it was found. {@code
   * tokenRuleStacks} maps a candidate token type to the rule call stacks (each outermost-first) at
   * which it was collected; this lets a consumer classify a literal token by its enclosing rules
   * (there may be more than one stack if the token can appear in multiple contexts at the caret).
   */
  public record CandidatesCollection(
      Map<Integer, List<Integer>> tokens,
      Map<Integer, CandidateRule> rules,
      Map<Integer, List<List<Integer>>> tokenRuleStacks) {}

  private record RuleWithStartToken(int startTokenIndex, int ruleIndex) {}

  private record FollowSetWithPath(
      IntervalSet intervals, List<Integer> path, List<Integer> following) {}

  private record FollowSetsHolder(
      List<FollowSetWithPath> sets, IntervalSet combined, boolean exhaustive) {}

  private record PipelineEntry(ATNState state, int tokenListIndex) {}

  /** Follow sets are a static property of a parser's ATN, so cache them per parser class. */
  private static final Map<String, Map<Integer, FollowSetsHolder>> FOLLOW_SETS_BY_ATN =
      new ConcurrentHashMap<>();

  private final Parser _parser;
  private final ATN _atn;

  private final Set<Integer> _ignoredTokens = new HashSet<>();
  private final Set<Integer> _preferredRules = new HashSet<>();

  private List<Token> _tokens;
  private List<Integer> _precedenceStack;
  private final Map<Integer, Map<Integer, Set<Integer>>> _shortcutMap = new HashMap<>();
  private Map<Integer, List<Integer>> _candidateTokens;
  private Map<Integer, CandidateRule> _candidateRules;
  private Map<Integer, List<List<Integer>>> _candidateTokenRuleStacks;

  public CodeCompletionCore(Parser parser) {
    _parser = parser;
    _atn = parser.getATN();
  }

  /** Tokens that should never appear as candidates (e.g. whitespace). */
  public Set<Integer> ignoredTokens() {
    return _ignoredTokens;
  }

  /** Rules that replace any token candidate they contain (e.g. return {@code nodeName}, not ID). */
  public Set<Integer> preferredRules() {
    return _preferredRules;
  }

  /**
   * Collects completion candidates for the token at {@code caretTokenIndex}. If {@code context} is
   * non-null the walk is limited to that rule (and rules it invokes).
   */
  public CandidatesCollection collectCandidates(int caretTokenIndex, ParserRuleContext context) {
    _shortcutMap.clear();
    _candidateTokens = new HashMap<>();
    _candidateRules = new HashMap<>();
    _candidateTokenRuleStacks = new HashMap<>();
    _precedenceStack = new ArrayList<>();

    int tokenStartIndex =
        context != null && context.start != null ? context.start.getTokenIndex() : 0;
    TokenStream tokenStream = _parser.getTokenStream();

    _tokens = new ArrayList<>();
    int offset = tokenStartIndex;
    while (true) {
      Token token = tokenStream.get(offset++);
      if (token == null) {
        break;
      }
      if (token.getChannel() == Token.DEFAULT_CHANNEL) {
        _tokens.add(token);
        if (token.getTokenIndex() >= caretTokenIndex || token.getType() == Token.EOF) {
          break;
        }
      }
      if (token.getType() == Token.EOF) {
        break;
      }
    }

    List<RuleWithStartToken> callStack = new ArrayList<>();
    int startRule = context != null ? context.getRuleIndex() : 0;
    processRule(_atn.ruleToStartState[startRule], 0, callStack, 0);

    return new CandidatesCollection(_candidateTokens, _candidateRules, _candidateTokenRuleStacks);
  }

  /** Records the rule call stack (outermost-first) at which {@code symbol} was collected. */
  private void recordTokenRuleStack(int symbol, List<RuleWithStartToken> callStack) {
    List<Integer> stack = new ArrayList<>(callStack.size());
    for (RuleWithStartToken entry : callStack) {
      stack.add(entry.ruleIndex());
    }
    _candidateTokenRuleStacks.computeIfAbsent(symbol, k -> new ArrayList<>()).add(stack);
  }

  private boolean checkPredicate(PredicateTransition transition) {
    return transition.getPredicate().eval(_parser, ParserRuleContext.EMPTY);
  }

  private boolean translateStackToRuleIndex(List<RuleWithStartToken> callStack) {
    if (_preferredRules.isEmpty()) {
      return false;
    }
    for (int i = 0; i < callStack.size(); i++) {
      if (translateToRuleIndex(i, callStack)) {
        return true;
      }
    }
    return false;
  }

  private boolean translateToRuleIndex(int i, List<RuleWithStartToken> callStack) {
    RuleWithStartToken entry = callStack.get(i);
    if (!_preferredRules.contains(entry.ruleIndex())) {
      return false;
    }
    List<Integer> path =
        callStack.subList(0, i).stream()
            .map(RuleWithStartToken::ruleIndex)
            .collect(Collectors.toList());

    boolean addNew = true;
    CandidateRule existing = _candidateRules.get(entry.ruleIndex());
    if (existing != null && existing.ruleList().equals(path)) {
      addNew = false;
    }
    if (addNew) {
      _candidateRules.put(entry.ruleIndex(), new CandidateRule(entry.startTokenIndex(), path));
    }
    return true;
  }

  private List<Integer> getFollowingTokens(Transition transition) {
    List<Integer> result = new ArrayList<>();
    Deque<ATNState> pipeline = new ArrayDeque<>();
    pipeline.push(transition.target);

    while (!pipeline.isEmpty()) {
      ATNState state = pipeline.pop();
      for (Transition outgoing : state.getTransitions()) {
        if (outgoing.getSerializationType() == Transition.ATOM) {
          if (!outgoing.isEpsilon()) {
            IntervalSet label = outgoing.label();
            if (label != null
                && label.size() == 1
                && !_ignoredTokens.contains(label.getMinElement())) {
              result.add(label.getMinElement());
              pipeline.push(outgoing.target);
            }
          } else {
            pipeline.push(outgoing.target);
          }
        }
      }
    }
    return result;
  }

  private FollowSetsHolder determineFollowSets(ATNState start, ATNState stop) {
    List<FollowSetWithPath> sets = new ArrayList<>();
    Deque<ATNState> stateStack = new ArrayDeque<>();
    Deque<Integer> ruleStack = new ArrayDeque<>();
    boolean exhaustive = collectFollowSets(start, stop, sets, stateStack, ruleStack);

    IntervalSet combined = new IntervalSet();
    for (FollowSetWithPath set : sets) {
      combined.addAll(set.intervals());
    }
    return new FollowSetsHolder(sets, combined, exhaustive);
  }

  private boolean collectFollowSets(
      ATNState s,
      ATNState stopState,
      List<FollowSetWithPath> followSets,
      Deque<ATNState> stateStack,
      Deque<Integer> ruleStack) {
    if (stateStack.contains(s)) {
      return true;
    }
    stateStack.push(s);

    if (s == stopState || s.getStateType() == ATNState.RULE_STOP) {
      stateStack.pop();
      return false;
    }

    boolean exhaustive = true;
    for (Transition transition : s.getTransitions()) {
      switch (transition.getSerializationType()) {
        case Transition.RULE -> {
          RuleTransition ruleTransition = (RuleTransition) transition;
          if (ruleStack.contains(ruleTransition.target.ruleIndex)) {
            continue;
          }
          ruleStack.push(ruleTransition.target.ruleIndex);
          boolean ruleExhaustive =
              collectFollowSets(transition.target, stopState, followSets, stateStack, ruleStack);
          ruleStack.pop();
          if (!ruleExhaustive) {
            exhaustive &=
                collectFollowSets(
                    ruleTransition.followState, stopState, followSets, stateStack, ruleStack);
          }
        }
        case Transition.PREDICATE -> {
          if (checkPredicate((PredicateTransition) transition)) {
            exhaustive &=
                collectFollowSets(transition.target, stopState, followSets, stateStack, ruleStack);
          }
        }
        case Transition.WILDCARD -> {
          followSets.add(
              new FollowSetWithPath(
                  IntervalSet.of(Token.MIN_USER_TOKEN_TYPE, _atn.maxTokenType),
                  new ArrayList<>(reversed(ruleStack)),
                  new ArrayList<>()));
        }
        default -> {
          if (transition.isEpsilon()) {
            exhaustive &=
                collectFollowSets(transition.target, stopState, followSets, stateStack, ruleStack);
          } else {
            IntervalSet label = transition.label();
            if (label != null && label.size() != 0) {
              if (transition.getSerializationType() == Transition.NOT_SET) {
                label = label.complement(Token.MIN_USER_TOKEN_TYPE, _atn.maxTokenType);
              }
              followSets.add(
                  new FollowSetWithPath(
                      label, new ArrayList<>(reversed(ruleStack)), getFollowingTokens(transition)));
            }
          }
        }
      }
    }
    stateStack.pop();
    return exhaustive;
  }

  private Set<Integer> processRule(
      RuleStartState startState,
      int tokenListIndex,
      List<RuleWithStartToken> callStack,
      int precedence) {
    Map<Integer, Set<Integer>> positionMap =
        _shortcutMap.computeIfAbsent(startState.ruleIndex, k -> new HashMap<>());
    if (positionMap.containsKey(tokenListIndex)) {
      return positionMap.get(tokenListIndex);
    }

    Set<Integer> result = new HashSet<>();

    Map<Integer, FollowSetsHolder> setsPerState =
        FOLLOW_SETS_BY_ATN.computeIfAbsent(_parser.getClass().getName(), k -> new HashMap<>());
    FollowSetsHolder followSets =
        setsPerState.computeIfAbsent(
            startState.stateNumber,
            k -> determineFollowSets(startState, _atn.ruleToStopState[startState.ruleIndex]));

    int startTokenIndex = _tokens.get(tokenListIndex).getTokenIndex();
    callStack.add(new RuleWithStartToken(startTokenIndex, startState.ruleIndex));

    if (tokenListIndex >= _tokens.size() - 1) {
      // At the caret.
      if (_preferredRules.contains(startState.ruleIndex)) {
        translateStackToRuleIndex(callStack);
      } else {
        for (FollowSetWithPath set : followSets.sets()) {
          List<RuleWithStartToken> fullPath = new ArrayList<>(callStack);
          for (int ruleIndex : set.path()) {
            fullPath.add(new RuleWithStartToken(startTokenIndex, ruleIndex));
          }
          if (!translateStackToRuleIndex(fullPath)) {
            for (int symbol : set.intervals().toList()) {
              if (!_ignoredTokens.contains(symbol)) {
                if (!_candidateTokens.containsKey(symbol)) {
                  _candidateTokens.put(symbol, set.following());
                } else if (!_candidateTokens.get(symbol).equals(set.following())) {
                  _candidateTokens.put(symbol, Collections.emptyList());
                }
                recordTokenRuleStack(symbol, fullPath);
              }
            }
          }
        }
      }
      if (!followSets.exhaustive()) {
        result.add(tokenListIndex);
      }
      callStack.remove(callStack.size() - 1);
      return result;
    } else {
      int currentSymbol = _tokens.get(tokenListIndex).getType();
      if (followSets.exhaustive() && !followSets.combined().contains(currentSymbol)) {
        callStack.remove(callStack.size() - 1);
        return result;
      }
    }

    if (startState.isLeftRecursiveRule) {
      _precedenceStack.add(precedence);
    }

    Deque<PipelineEntry> statePipeline = new ArrayDeque<>();
    statePipeline.push(new PipelineEntry(startState, tokenListIndex));

    while (!statePipeline.isEmpty()) {
      PipelineEntry currentEntry = statePipeline.pop();
      int currentSymbol = _tokens.get(currentEntry.tokenListIndex()).getType();
      boolean atCaret = currentEntry.tokenListIndex() >= _tokens.size() - 1;

      if (currentEntry.state().getStateType() == ATNState.RULE_STOP) {
        result.add(currentEntry.tokenListIndex());
        continue;
      }

      for (Transition transition : currentEntry.state().getTransitions()) {
        switch (transition.getSerializationType()) {
          case Transition.RULE -> {
            RuleTransition ruleTransition = (RuleTransition) transition;
            Set<Integer> endStatus =
                processRule(
                    (RuleStartState) transition.target,
                    currentEntry.tokenListIndex(),
                    callStack,
                    ruleTransition.precedence);
            for (int position : endStatus) {
              statePipeline.push(new PipelineEntry(ruleTransition.followState, position));
            }
          }
          case Transition.PREDICATE -> {
            if (checkPredicate((PredicateTransition) transition)) {
              statePipeline.push(
                  new PipelineEntry(transition.target, currentEntry.tokenListIndex()));
            }
          }
          case Transition.PRECEDENCE -> {
            PrecedencePredicateTransition predTransition =
                (PrecedencePredicateTransition) transition;
            if (predTransition.precedence >= _precedenceStack.get(_precedenceStack.size() - 1)) {
              statePipeline.push(
                  new PipelineEntry(transition.target, currentEntry.tokenListIndex()));
            }
          }
          case Transition.WILDCARD -> {
            if (atCaret) {
              if (!translateStackToRuleIndex(callStack)) {
                for (int token :
                    IntervalSet.of(Token.MIN_USER_TOKEN_TYPE, _atn.maxTokenType).toList()) {
                  if (!_ignoredTokens.contains(token)) {
                    _candidateTokens.put(token, Collections.emptyList());
                    recordTokenRuleStack(token, callStack);
                  }
                }
              }
            } else {
              statePipeline.push(
                  new PipelineEntry(transition.target, currentEntry.tokenListIndex() + 1));
            }
          }
          default -> {
            if (transition.isEpsilon()) {
              statePipeline.push(
                  new PipelineEntry(transition.target, currentEntry.tokenListIndex()));
              continue;
            }
            IntervalSet set = transition.label();
            if (set != null && set.size() != 0) {
              if (transition.getSerializationType() == Transition.NOT_SET) {
                set = set.complement(Token.MIN_USER_TOKEN_TYPE, _atn.maxTokenType);
              }
              if (atCaret) {
                if (!translateStackToRuleIndex(callStack)) {
                  List<Integer> list = set.toList();
                  boolean hasTokenSequence = list.size() == 1;
                  for (int symbol : list) {
                    if (!_ignoredTokens.contains(symbol)) {
                      List<Integer> followingTokens =
                          hasTokenSequence
                              ? getFollowingTokens(transition)
                              : Collections.emptyList();
                      if (!_candidateTokens.containsKey(symbol)) {
                        _candidateTokens.put(symbol, followingTokens);
                      } else {
                        _candidateTokens.put(
                            symbol,
                            longestCommonPrefix(followingTokens, _candidateTokens.get(symbol)));
                      }
                      recordTokenRuleStack(symbol, callStack);
                    }
                  }
                }
              } else if (set.contains(currentSymbol)) {
                statePipeline.push(
                    new PipelineEntry(transition.target, currentEntry.tokenListIndex() + 1));
              }
            }
          }
        }
      }
    }

    callStack.remove(callStack.size() - 1);
    if (startState.isLeftRecursiveRule) {
      _precedenceStack.remove(_precedenceStack.size() - 1);
    }

    positionMap.put(tokenListIndex, result);
    return result;
  }

  /**
   * Returns {@code ruleStack} bottom-to-top (a Deque iterates top-to-bottom when used as a stack).
   */
  private static List<Integer> reversed(Deque<Integer> ruleStack) {
    List<Integer> list = new ArrayList<>(ruleStack);
    Collections.reverse(list);
    return list;
  }

  private static List<Integer> longestCommonPrefix(List<Integer> a, List<Integer> b) {
    int minLength = Math.min(a.size(), b.size());
    List<Integer> result = new ArrayList<>();
    for (int i = 0; i < minLength; i++) {
      if (a.get(i).equals(b.get(i))) {
        result.add(a.get(i));
      } else {
        break;
      }
    }
    return result;
  }
}
