package org.batfish.common.datamodel.questions;

public enum QuestionType {
   ACL_REACHABILITY,
   COMPARE_SAME_NAME,
   DESTINATION,
   INGRESS_PATH,
   LOCAL_PATH,
   MULTIPATH,
   NEIGHBORS,
   NODES,
   PROTOCOL_DEPENDENCIES,
   REACHABILITY,
   REDUCED_REACHABILITY,
   TRACEROUTE,
   VERIFY
}
