package(default_visibility = ["//visibility:public"])

java_library(
    name = "f5_bigip_imish_base_parser",
    srcs = [
        ":F5BigipImishBaseParser.java",
    ],
    deps = [
        "//projects/batfish-common-protocol:parser_common",
        "@antlr4_runtime//:compile",
        "@com_google_guava_guava//jar",
        "@jsr305//:compile",
    ],
)
