package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

java_import(
    name = "z3",
    jars = ["com.microsoft.z3-2018-01-12-450f3c9b459d128135abb5bbd4fa0508fe26bfae.jar"],
    srcjar = "com.microsoft.z3-2018-01-12-450f3c9b459d128135abb5bbd4fa0508fe26bfae-sources.jar",
)
