from pybatfish.util.batfish_exception import BatfishException

class BfResponse:
    '''
    Class to describe the responses generated by batfish client
    '''
    
    Undefined = -1
    Success = 0
    ConnectionFailure = 1
    UnknownFailure = 2
    _MaxCodeValue = 2

    def __init__(self, code=-1, response=None):
        if (code < BfResponse.Undefined or code > BfResponse._MaxCodeValue):
            raise BatfishException("Illegal code for BfResponse")
        
        self.code = code
        self.response = response
                    
    