#!/bin/bash
COORDINATOR="${BASH_SOURCE[0]}"
COORDINATOR_PATH="$(dirname "$COORDINATOR")"
ALLINONE_PATH="${COORDINATOR_PATH}/../allinone"
ALLINONE_JAR="$ALLINONE_PATH/target/allinone-bundle-${BATFISH_VERSION}.jar"
ALLINONE_QUESTIONS_PATH="${QUESTIONS_PATH}"
CPSEP=":"
if batfish_cygwin; then
   ALLINONE_JAR="$(cygpath -w "$ALLINONE_JAR")"
   ALLINONE_QUESTIONS_PATH="$(cygpath -w "${QUESTIONS_PATH}")"
   CPSEP=";"
fi
if [[ " $@ " =~ " -templatedirs " ]]; then
  ALLINONE_TEMPLATEDIRS_ARG=()
else
  ALLINONE_TEMPLATEDIRS_ARG=(-templatedirs "${ALLINONE_QUESTIONS_PATH}")
fi

java ${COORDINATOR_JAVA_ARGS} -cp "${ALLINONE_JAR}${CPSEP}${COORDINATOR_CLASSPATH}" org.batfish.coordinator.Main "${ALLINONE_TEMPLATEDIRS_ARG[@]}" "$@"

