package org.batfish.logicblox;

public enum LBValueType {
   ENTITY_INDEX_BGP_ADVERTISEMENT,
   ENTITY_INDEX_FLOW,
   ENTITY_INDEX_INT,
   ENTITY_INDEX_NETWORK,
   ENTITY_INDEX_ROUTE,
   ENTITY_REF_ADVERTISEMENT_TYPE,
   ENTITY_REF_AS_PATH,
   ENTITY_REF_AUTONOMOUS_SYSTEM,
   ENTITY_REF_FLOW_TAG,
   ENTITY_REF_INT,
   ENTITY_REF_INTERFACE,
   ENTITY_REF_IP,
   ENTITY_REF_NODE,
   ENTITY_REF_ORIGIN_TYPE,
   ENTITY_REF_POLICY_MAP,
   ENTITY_REF_ROUTING_PROTOCOL,
   ENTITY_REF_STRING,
   FLOAT,
   INT,
   STRING
}
