#!/bin/bash
BATFISH=${BASH_SOURCE[0]}
BATFISH_PATH=$(dirname $BATFISH)
BATFISH_JAR=$BATFISH_PATH/out/batfish.jar
if [[ $(uname) == *"Cygwin"* ]]; then
   BATFISH_JAR="$(cygpath -w $BATFISH_JAR)"
fi
java -jar "$BATFISH_JAR" $@

