package org.batfish.representation.juniper;

public enum JunosApplicationSet {
  JUNOS_CIFS,
  JUNOS_MGCP,
  JUNOS_MS_RPC,
  JUNOS_MS_RPC_ANY,
  JUNOS_MS_RPC_IIS_COM,
  JUNOS_MS_RPC_MSEXCHANGE,
  JUNOS_MS_RPC_WMIC,
  JUNOS_ROUTING_INBOUND,
  JUNOS_SUN_RPC,
  JUNOS_SUN_RPC_ANY,
  JUNOS_SUN_RPC_MOUNTD,
  JUNOS_SUN_RPC_NFS,
  JUNOS_SUN_RPC_NFS_ACCESS,
  JUNOS_SUN_RPC_NLOCKMGR,
  JUNOS_SUN_RPC_PORTMAP,
  JUNOS_SUN_RPC_RQUOTAD,
  JUNOS_SUN_RPC_RUSERD,
  JUNOS_SUN_RPC_SADMIND,
  JUNOS_SUN_RPC_SPRAYD,
  JUNOS_SUN_RPC_STATUS,
  JUNOS_SUN_RPC_WALLD,
  JUNOS_SUN_RPC_YPBIND,
  JUNOS_SUN_RPC_YPSERV


}
