package(
    default_testonly = True,
    default_visibility = [
        "//projects/allinone/src/test/java/org/batfish/question/routes:__subpackages__",
    ],
)

filegroup(
    name = "configs",
    srcs = [
        "r1",
        "r2",
    ],
)
