package org.batfish.question;

public enum QuestionType {
   ACL_REACHABILITY,
   DESTINATION,
   INGRESS_PATH,
   LOCAL_PATH,
   MULTIPATH,
   PROTOCOL_DEPENDENCIES,
   REACHABILITY,
   REDUCED_REACHABILITY,
   TRACEROUTE,
   VERIFY
}
