package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "bgp-best-path-export",
    srcs = glob(
        ["**"],
        exclude = ["BUILD"],
    ),
)
