package org.batfish.datamodel.questions;

public enum QuestionType {
   ACL_REACHABILITY,
   BGP_ADVERTISEMENTS,
   BGP_SESSION_CHECK,
   COMPARE_SAME_NAME,
   IPSEC_VPN_CHECK,
   ISIS_LOOPBACKS,
   LOCAL_PATH,
   MULTIPATH,
   NEIGHBORS,
   NODES,
   OSPF_LOOPBACKS,
   PROTOCOL_DEPENDENCIES,
   REACHABILITY,
   REDUCED_REACHABILITY,
   ROUTES,
   TRACEROUTE
}
