package org.batfish.datamodel.questions;

public enum QuestionType {
   ACL_REACHABILITY,
   BGP_ADVERTISEMENTS,
   BGP_SESSION_CHECK,
   COMPARE_SAME_NAME,
   IPSEC_VPN_CHECK,
   ISIS_LOOPBACKS,
   LOCAL_PATH,
   MULTIPATH,
   NEIGHBORS,
   NODES,
   OSPF_LOOPBACKS,
   PAIRWISE_VPN_CONNECTIVITY,
   PROTOCOL_DEPENDENCIES,
   REACHABILITY,
   REDUCED_REACHABILITY,
   ROUTES,
   SELF_ADJACENCIES,
   TRACEROUTE,
   UNIQUE_BGP_PREFIX_ORIGINATION,
   UNIQUE_IP_ASSIGNMENTS
}
