package org.batfish.datamodel.questions;

public enum QuestionType {
   ACL_REACHABILITY,
   BGP_ADVERTISEMENTS,
   COMPARE_SAME_NAME,
   LOCAL_PATH,
   MULTIPATH,
   NEIGHBORS,
   NODES,
   PROTOCOL_DEPENDENCIES,
   REACHABILITY,
   REDUCED_REACHABILITY,
   TRACEROUTE
}
