package org.batfish.representation.juniper;

import static org.hamcrest.Matchers.equalTo;
import static org.junit.Assert.assertThat;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import java.util.ArrayList;
import java.util.List;
import org.batfish.datamodel.ExprAclLine;
import org.batfish.datamodel.HeaderSpace;
import org.batfish.datamodel.IpProtocol;
import org.batfish.datamodel.LineAction;
import org.batfish.datamodel.NamedPort;
import org.batfish.datamodel.SubRange;
import org.batfish.datamodel.acl.MatchHeaderSpace;
import org.junit.Test;

/** Test for {@link FwFromJunosApplication} */
public class FwFromJunosApplicationTest {
  @Test
  public void testApplyTo_bgp() {
    JunosApplication junosApp = JunosApplication.JUNOS_BGP;
    FwFromJunosApplication from = new FwFromJunosApplication(junosApp);

    List<ExprAclLine> lines = new ArrayList<>();
    HeaderSpace.Builder hsBuilder = HeaderSpace.builder();

    from.applyTo(null, hsBuilder, LineAction.PERMIT, lines, null);

    assertThat(
        lines,
        equalTo(
            ImmutableList.of(
                new ExprAclLine(
                    LineAction.PERMIT,
                    new MatchHeaderSpace(
                        HeaderSpace.builder()
                            .setIpProtocols(ImmutableSet.of(IpProtocol.TCP))
                            .setDstPorts(
                                ImmutableSet.of(SubRange.singleton(NamedPort.BGP.number())))
                            .build()),
                    null,
                    junosApp.getBaseApplication().getTermTracingName(null)))));
  }

  @Test
  public void testApplyTo_smb() {
    // this application has multiple terms. since all terms are generated by BF, the tracing element
    // should only show the application name
    JunosApplication junosApp = JunosApplication.JUNOS_SMB;
    FwFromJunosApplication from = new FwFromJunosApplication(junosApp);

    List<ExprAclLine> lines = new ArrayList<>();
    HeaderSpace.Builder hsBuilder = HeaderSpace.builder();

    from.applyTo(null, hsBuilder, LineAction.PERMIT, lines, null);

    assertThat(
        lines,
        equalTo(
            ImmutableList.of(
                new ExprAclLine(
                    LineAction.PERMIT,
                    new MatchHeaderSpace(
                        HeaderSpace.builder()
                            .setIpProtocols(ImmutableSet.of(IpProtocol.TCP))
                            .setDstPorts(
                                ImmutableSet.of(
                                    SubRange.singleton(NamedPort.MICROSOFT_DS.number())))
                            .build()),
                    null,
                    junosApp.getBaseApplication().getTermTracingName(null)),
                new ExprAclLine(
                    LineAction.PERMIT,
                    new MatchHeaderSpace(
                        HeaderSpace.builder()
                            .setIpProtocols(ImmutableSet.of(IpProtocol.TCP))
                            .setDstPorts(
                                ImmutableSet.of(SubRange.singleton(NamedPort.NETBIOS_SSN.number())))
                            .build()),
                    null,
                    junosApp.getBaseApplication().getTermTracingName(null)))));
  }

  @Test
  public void testApplyTo_any() {
    JunosApplication junosApp = JunosApplication.ANY;
    FwFromJunosApplication from = new FwFromJunosApplication(junosApp);

    List<ExprAclLine> lines = new ArrayList<>();
    HeaderSpace.Builder hsBuilder = HeaderSpace.builder();

    from.applyTo(null, hsBuilder, LineAction.PERMIT, lines, null);

    assertThat(
        lines,
        equalTo(
            ImmutableList.of(
                new ExprAclLine(
                    LineAction.PERMIT,
                    new MatchHeaderSpace(HeaderSpace.builder().build()),
                    null,
                    junosApp.getBaseApplication().getTermTracingName(null)))));
  }
}
