package org.batfish.representation.cisco;

public enum RouteMapSetType {
  ADDITIVE_COMMUNITY,
  ADDITIVE_COMMUNITY_LIST,
  AS_PATH_PREPEND,
  COMMUNITY,
  COMMUNITY_LIST,
  COMMUNITY_NONE,
  DELETE_COMMUNITY,
  LOCAL_PREFERENCE,
  METRIC,
  NEXT_HOP,
  NEXT_HOP_PEER_ADDRESS,
  ORIGIN_TYPE,
  WEIGHT
}
