package org.batfish.datamodel.ospf;

/** Enum for possible status values for OSPF sessions */
public enum OspfSessionStatus {
  AREA_INVALID,
  AREA_MISMATCH,
  AREA_TYPE_MISMATCH,
  DEAD_INTERVAL_MISMATCH,
  DUPLICATE_ROUTER_ID,
  ESTABLISHED,
  HELLO_INTERVAL_MISMATCH,
  MTU_MISMATCH,
  NETWORK_TYPE_MISMATCH,
  PASSIVE_MISMATCH,
  PROCESS_INVALID,
  UNKNOWN_COMPATIBILITY_ISSUE,
}
