name: Bazel Steward

on:
  workflow_dispatch:
  schedule:
    - cron: '07 12 * * 1' # runs Mondays at 1207 UTC which is sensible US/Pacific

jobs:
  bazel-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: VirtusLab/bazel-steward@21a745e047b04953192bdb2f590a1ef445732ad9
        with:
          configuration-path: "./.bazel-steward.yaml"
