name: Maven
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Tests + Coverage
      run: |
           mvn -B -f projects/pom.xml verify -DskipTests=false -Djacoco.skip=false
    - name: Archive built jar
      uses: actions/upload-artifact@v3
      with:
        name: maven-built-jar
        path: projects/allinone/target/*bundle*.jar
