name: OWASP Vulnerability Scan
on:
  schedule:
    - cron: '0 15 * * *'  # 8AM Pacific; daily
  workflow_dispatch:

jobs:
  get_date:
    name: ":clock: Get Date"
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=ymd::$(TZ=America/Los_Angeles date +'%Y-%m-%d')"
    outputs:
      ymd: ${{ steps.date.outputs.ymd }}
  format:
    runs-on: ubuntu-latest
    needs:
      - get_date
    steps:
      - uses: actions/checkout@v3
      - name: OWASP cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/owasp"
          key: owasp-${{ hashFiles('tools/run_owasp.sh') }}-${{ needs.get_date.outputs.ymd }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Java Formatting
        run: tools/run_owasp.sh
