package(default_visibility = ["//projects/symbolic:__pkg__"])

load("@batfish//skylark:junit.bzl", "junit_tests")

java_library(
    name = "state",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "@jsr305//:compile",
    ],
)
